name: Feature Request
description: Suggest an enhancement or new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the information below to help us understand your idea.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm frustrated when...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've also thought about...
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: Here's a mockup / example...
    validations:
      required: false
      
  - type: dropdown
    id: willing
    attributes:
      label: Are you willing to contribute?
      description: Would you be willing to implement this feature yourself?
      options:
        - "Yes, I can implement this"
        - "Yes, with guidance"
        - "No, but I can help test"
        - "No"
    validations:
      required: false
